#!/bin/bash
# EXACT COMMANDS TO RUN - Copy and paste these in order

echo "================================================================"
echo "PaaS Platform Deployment - Exact Commands"
echo "================================================================"
echo ""
echo "Run these commands in order:"
echo ""
echo "# 1. INSTALL PREREQUISITES (if not already installed)"
echo "sudo pacman -S vagrant ansible libvirt qemu dnsmasq ebtables dmidecode"
echo ""
echo "# 2. START LIBVIRT"
echo "sudo systemctl start libvirtd"
echo "sudo systemctl enable libvirtd"
echo ""
echo "# 3. ADD USER TO LIBVIRT GROUP (then logout/login)"
echo "sudo usermod -a -G libvirt \$USER"
echo ""
echo "# 4. INSTALL VAGRANT PLUGIN"
echo "vagrant plugin install vagrant-libvirt"
echo ""
echo "# 5. CHECK PREREQUISITES"
echo "cd /home/xpert/Desktop/Projects/platform-deployement"
echo "./setup.sh"
echo ""
echo "# 6. DEPLOY THE PLATFORM"
echo "cd infrastructure"
echo "vagrant up"
echo ""
echo "# 7. ACCESS THE PLATFORM"
echo "Open browser: http://192.168.121.10:5000"
echo "         or: http://localhost:5000"
echo ""
echo "================================================================"
echo "ADMIN COMMANDS (Pool Management)"
echo "================================================================"
echo ""
echo "# RUN ADMIN HELPER SCRIPT (Easy Way)"
echo "./admin.sh"
echo ""
echo "# OR use SSH directly"
echo "ssh -t vagrant@192.168.121.183 \"sudo bash /opt/my-paas/admin_helper.sh\""
echo ""
echo "# QUICK ADMIN COMMANDS"
echo "# Show pool status"
echo "vagrant ssh -c \"cd /opt/my-paas && source venv/bin/activate && python pool_manager.py --status\""
echo ""
echo "# List all users"
echo "vagrant ssh -c \"cd /opt/my-paas && source venv/bin/activate && python -c 'from app import app, db, User; app.app_context().push(); users = User.query.all(); [print(f\\\"{u.id}: {u.username} ({len(u.containers)} containers)\\\") for u in users]'\""
echo ""
echo "# Check Flask status"
echo "vagrant ssh -c \"pgrep -f 'flask run' && echo 'Flask is running' || echo 'Flask is stopped'\""
echo ""
echo "# Restart Flask"
echo "vagrant ssh -c \"sudo pkill -f 'flask run' && cd /opt/my-paas && source venv/bin/activate && nohup flask run --host=0.0.0.0 > flask.log 2>&1 &\""
echo ""
echo "================================================================"
echo "ALTERNATIVE: Use Makefile commands"
echo "================================================================"
echo ""
echo "make help          # Show all available commands"
echo "make check         # Check prerequisites"
echo "make up            # Deploy the platform"
echo "make ssh           # SSH into the VM"
echo "make logs          # View application logs"
echo "make status        # Check VM status"
echo "make halt          # Stop the VM"
echo "make destroy       # Destroy the VM"
echo ""
echo "================================================================"
